services:
  db:
    image: mysql:8.0
    container_name: misaka_mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--expire_logs_days=3"
      - "--binlog_expire_logs_seconds=259200"
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "d*^hlgaYqV1QkgI8"
      MYSQL_DATABASE: danmuapi
      MYSQL_USER: danmuapi
      MYSQL_PASSWORD: "nLpOh@39VmtxAU0$"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

  app:
    image: sapphirecho8/misaka_danmu_server_plus:latest
    container_name: misaka_danmu_server_plus
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: Asia/Shanghai
      DANMUAPI_DATABASE__TYPE: mysql
      DANMUAPI_DATABASE__HOST: db
      DANMUAPI_DATABASE__PORT: 3306
      DANMUAPI_DATABASE__NAME: danmuapi
      DANMUAPI_DATABASE__USER: danmuapi
      DANMUAPI_DATABASE__PASSWORD: "nLpOh@39VmtxAU0$"
      DANMUAPI_SERVER__PORT: 7768
      DANMUAPI_ADMIN__INITIAL_USER: admin
      DANMUAPI_ADMIN__INITIAL_PASSWORD: "CrS@Tp9@Xl92sXGz"
      DANMUAPI_JWT__SECRET_KEY: "2b6d1beac43cd6fa97526ad612d4fa7dc8d8859d2257499329abacc54e0f92cf"
    ports:
      - "7768:7768"
    volumes:
      - config-data:/app/config

volumes:
  config-data:
  mysql-data:
